### ISSUE TITLE
Please avoid genedered language 

### ISSUE THREAD

**Issue by marcoscaceres** [soapdog/firefoxos-quick-guide#10]
Be careful with gender specific language. Avoid using "he" (instead use "they", which is gender neutral - or "he or she".... and when using a single form, it's better to use she... just to stick it to the man :smile: ).

**Comment by soapdog** [comment]
Yes. In Portuguese this is not a big deal but I agree that in English I should use gendered neutral ones and mix and match he and she.

**Comment by marcoscaceres** [comment]
I've been correcting this as I go. I will close this for now as I already fixed other occurrences, and will fix anything I find in other chapters.
