### ISSUE TITLE
Unlimited storage request

### ISSUE THREAD

**Issue by marcoscaceres** [soapdog/firefoxos-quick-guide#11]
I'm a bit worried that you are encouraging people to request unlimited storage on a device through IndexedDB. Requesting such a thing without actual justification to do so would get the application rejected from the firefox marketplace. This applies to all APIs.

**Comment by soapdog** [comment]
Agreed but since I am about to add photo attachment to the app, we'll need that flag there with the correct justification since we're about to store some blobs. This will justify the use of IDB and the permission.

**Comment by marcoscaceres** [comment]
Ok, that's more reasonable - but I'm still wondering what the limit actually is? That should be mentioned in the book.  

I added a bunch of warnings to developers about this issue already in two chapters, but talking about the MB limit imposed by FxOS is important.
