### ISSUE TITLE
Using IndexedDB in first example is too complicated

### ISSUE THREAD

**Issue by marcoscaceres** [soapdog/firefoxos-quick-guide#12]
Do you _really_ need to use IDB in the first example? IDB is the most complicated storage API on the Web (and generally just really confusing to understand).

Can't you use localStorage instead for such simple data?

**Comment by marcoscaceres** [comment]
I'll note that it takes 30 lines (!) to save a memo, while you could just do it in like 3 lines with localStorage.

**Comment by soapdog** [comment]
Yes it does and it would be simpler to use localStorage but the idea was to show a different API and if I reorganize the code and add something like attachments such as photos to a note then we're going to need IDB anyway. I'm thinking about reorganizing the code and adding attachments, this way the sample exposes the developer to two new APIs and maybe even add some device storage to export notes to text files.

**Comment by marcoscaceres** [comment]
With photos, it might be likely. You could still convert a photo to a data URL and put it into localStorage.... but, let's see how this goes with the first batch of people that read this. It might be good to distribute this to people in the Gaia team once we are finished with this set of changes.

**Comment by Ryuno-Ki** [comment]
localStorage is banned on Firefox OS Gaia due to I/O performance penalties. async_storage is an alternative (using IDB with a localStorage-like interface). You'll find it in the gaia repo ;-)
