### ISSUE TITLE
Example code could be greatly reduced

### ISSUE THREAD

**Issue by marcoscaceres** [soapdog/firefoxos-quick-guide#13]
I think you should just include the source files and force yourself to reduce the complexity of the code... specially in the first coding chapter. By removing indexedDB, and organizing the code better, I think the whole app could be about 100 lines of code max.  

I can help you with that, but I need you to update the chapters so that they include the code.

**Comment by soapdog** [comment]
I don't want to lose IndexedDB on that example. Its a long example but it is more real than if I just use localStorage. I agree that the code needs better reorganization. Specially the part that creates the list view.
