### ISSUE TITLE
Using document.getElementById everywhere is really ugly

### ISSUE THREAD

**Issue by marcoscaceres** [soapdog/firefoxos-quick-guide#14]
You can make your code much more legible by doing that following:

``` JS
//Emulate query selection from JQuery 
var $ = $ || function(selector){
   return document.getElementById(selector); 
}

```

Then the code will be much easier to read.

**Comment by marcoscaceres** [comment]
Actually, changed my mind about this one. It's still ugly, but need to use a mix of querySelector and querySelectorAll to fix this.

**Comment by marcoscaceres** [comment]
Will leave this open so it can be fixed later...

**Comment by soapdog** [comment]
Its ugly but it is more direct. Every time I pick someone code and I see a $, I wonder if the person is using jQuery, Zepto or redefining $. I like clear code, for me it doesn't matter if I type more commands.

On a side note, there are some people that are unaware of querySelector... argh!

**Comment by marcoscaceres** [comment]
Yeah, for the reasons above I also become unsure. Let's stick with what you got, but I think we can make some clarifications in a future version (0.3 release). 

Maybe file a bug for that.
