### ISSUE TITLE
Front matter split into chapters

### ISSUE THREAD

**Issue by marcoscaceres** [soapdog/firefoxos-quick-guide#21]
The front matter is currently splitting in to chapters... would be good to make sure all that content is grouped into sub-sections instead.

This should be fixed with some urgency.

**Comment by soapdog** [comment]
Thats the way that Leanpub treats its frontmatter. I will fix that moving them to level two navigation and issue an update. Just don't know if I should issue an update right now...

**Comment by marcoscaceres** [comment]
Maybe mark it for 0.3.

**Comment by soapdog** [comment]
I've fixed it but I am not updating the published version today. This fix will be added along with the other updates after the first couple days worth of feedback.
