### ISSUE TITLE
New argument for the guide

### ISSUE THREAD

**Issue by Mte90** [soapdog/firefoxos-quick-guide#27]
I had already started thinking about writing a guide for Firefoxos and I wanted to include these topics. So I translated the guide and I saw these deficiencies.
I wanted to make a guide focused on the boilerplate because it contains very basic material. Also because this is boilerplate what I have learned how to work with Firefox OS then I think it is an important element.
What do you think?
- Guidelines for the marketplace https://developer.mozilla.org/en-US/Marketplace/Submission/Marketplace_review_criteria 
- Details for the manifest https://developer.mozilla.org/en-US/Apps/Developing/Manifest
- ADB Helper / https://ftp.mozilla.org/pub/mozilla.org/labs/fxos-simulator/
- https://github.com/fabi1cazenave/webL10n
- http://mozilla.github.io/brick/
- https://github.com/robnyman/Firefox-OS-Boilerplate-App
- Web activity
- API specific for Firefox OS
- https://github.com/Mte90/moz-polyfills (my polyfill for the webactivity)
- Update the dashboard of the simulator because integrated in firefox

**Comment by Mte90** [comment]
At the moment i have written in italian the part for adb, guidelines for the marketplace, multilanguage and manifest.
Now i'm working on the part for the boilerplate.
I'm waiting a your feedback for these arguments.

**Comment by Mte90** [comment]
Now i have written all in italian, the missing part is the Update of the dashboard of the simulator because integrated in firefox.

**Comment by Mte90** [comment]
After the discussion on twitter (https://twitter.com/Mte90Net/status/419241905478582273) i post the content of the page of simulator (https://addons.mozilla.org/it/firefox/addon/firefox-os-simulator/) on AMO:

```
Important! This add-on is compatible with Firefox 24/25 and Firefox OS 1.1.  
To test apps using Firefox 26+ with Firefox OS 1.2+, please use the new App Manager built into Firefox! For more info, see the Introducing the Firefox OS App Manager Hacks blog post and the Using the App Manager MDN documentation.
```

Now the better solution for not use software outdated is use the app manager .
For backwards compatibility we can leave the older text for the simulator FFOS 1.1.

**Comment by Mte90** [comment]
The italian translation for this version it's complete!
Now i'm waiting for a response for these new arguments!

**Comment by soapdog** [comment]
They recommend using app manager only for testing with 1.2+ but that version is not on the market. There are no retail phones available with it right now. 

Most developers are not using keons/peaks and do not have access to 1.2+ builds.

I agree that material for App Manager is needed but I don't think it can be included right now because it will confuse the developers. I am thinking about it. Yes, you're probably right. I will check if there is a good way of adding the app manager material.

Be aware that Firefox Marketplace still advise testing on 1.1 because thats the version on the streets and that version does not support app manager.

**Comment by Mte90** [comment]
The developers can flash the unofficial roms for their phone.
If the developers can test their apps on new versions of FirefoxOS the producers of the phones not update the device so there is no app that supports them.

Changing the subject I would like to present the guide in Italian in a few weeks so i want to know if present this version or the new with this new content.

**Comment by Ryuno-Ki** [comment]
AFAIK, Alcatel won't ship Fx OS v1.2 and instead skip it. So users (like me in Germany) have to wait up to April to hopefully receive v1.3.

So far, only Geeksphone users and ZTE device owners can use v1.3.

**Comment by Mte90** [comment]
There are unofficial roms for the Alcatel One Touch Fire :-P

**Comment by Ryuno-Ki** [comment]
I have never seen one of them. Well, I don't think, they should be linked publicly here?

**Comment by Mte90** [comment]
removed :-D

**Comment by soapdog** [comment]
Guys,

I will add App Manager related chapters soon. I am working on an updated version and your contributions make all this worthwhile. Thanks so much.

**Comment by Mte90** [comment]
I have written some of this topics in italian, if you want i can translate in english.

**Comment by Ryuno-Ki** [comment]
Would appreciate your contribution, Mte :-)

**Comment by Mte90** [comment]
I would start the translation only if needed. 
For this reason i have do it this list of new topics :-/

**Comment by soapdog** [comment]
App Manager section added.
