### ISSUE TITLE
Using OSNs

### ISSUE THREAD

**Issue by Ryuno-Ki** [soapdog/firefoxos-quick-guide#28]
Hello,

finally read through the Quick Guide :-)

You may ask leanpub, to use [OSN](https://en.wikipedia.org/wiki/Old-style_numeral)s in a future version? It's easier to read in my opinion :-)

**Comment by soapdog** [comment]
OSN looks beautiful but we don't have control over that with leanpub... :-(

**Comment by Ryuno-Ki** [comment]
What a bummer!

It's a CSS property *FYI*
