### ISSUE TITLE
Handling warning boxes

### ISSUE THREAD

**Issue by Ryuno-Ki** [soapdog/firefoxos-quick-guide#30]
Hello,

another pinpoint for leanpub: In firstapp.md (lines 180 + 225 or so) you used <code>A></code> to embed the following content in a box. While warning boxes (those with a leading <code>W></code>) are correctly displayed, I'm missing an icon for those <code>A></code> boxes …

**Comment by soapdog** [comment]
Yep, the handling of boxes is not as flexible as I wanted. I chose the `A>` because it had no icon.
