### ISSUE TITLE
Removing orphans

### ISSUE THREAD

**Issue by Ryuno-Ki** [soapdog/firefoxos-quick-guide#31]
Hello, me again :)

I'm wondering, what kind of typesetters are working at leanpub …

I found [orphans](https://en.wikipedia.org/wiki/Orphan_%28typesetting%29), that is, the heading "Hosted Apps".

The other one is your image of the "permission request screen" -> Boy, there's a [screenshot feature](http://mzl.la/12STuvF) for that ;-)

Otherwise ask them for resizing the image bevor delivering the PDF.

**Comment by soapdog** [comment]
I wrote the book in a single night. The photo was chosen to make the book more human. I may replace that.

As for typesetters at leanpub, I have no clue.
