### ISSUE TITLE
Retesting "packaged app installation outside of the marketplace"

### ISSUE THREAD

**Issue by Ryuno-Ki** [soapdog/firefoxos-quick-guide#33]
Hello,

have you tested the installation of packaged apps outside of the Mozilla Marketplace again? Does it work with v1.1+?

In this case, please edit the distribution.md!

**Comment by Mte90** [comment]
I've tried to install a packaged app in the firefox os 1.3 with the browser without problems.

**Comment by soapdog** [comment]
Packaged apps appear to be working but privileged apps are not :-1:
