### ISSUE TITLE
First app - button in markup

### ISSUE THREAD

**Issue by marcoscaceres** [soapdog/firefoxos-quick-guide#8]
This is a bit strange/not ideal:

``` HTML
        <button id="back-to-list"><span class="icon icon-back">back</span>
        </button>
```

Why not?

``` HTML
        <button id="back-to-list" class="icon icon-back">back</button>
```

Or is it that Gaia Building Blocks are broken with regards to this?

**Comment by marcoscaceres** [comment]
The same applies also to:

``` HTML
            <a id="share-memo" href="#"><span class="icon icon-share">share</span>
            </a>
```

The span should not be needed.

**Comment by soapdog** [comment]
Its the building blocks doing their funky thing again. Thats one of my main criticisms of them. It's much more complicated that it needs to be. I agree that it uses way more nodes than required for the same effect.

**Comment by marcoscaceres** [comment]
oh dear :( Ok, might need to add a note that this is not your fault. Any Web developer that's reading this book for the first time is going to be looking at this and wondering why the markup is so verbose.

**Comment by marcoscaceres** [comment]
You can probably mark this as WONTFIX and close then.
