### ISSUE TITLE
First app - use of `menu` element 

### ISSUE THREAD

**Issue by marcoscaceres** [soapdog/firefoxos-quick-guide#9]
I think your use of the `menu` element is invalid. The HTML5 specification states that:

>    If the element's type attribute is in the `toolbar` state: either zero or more li and script-supporting elements, or, flow content.
>    If the element's type attribute is in the `popup` menu state: in any order, zero or more menuitem elements, zero or more hr elements, zero or more menu elements whose type attributes are in the popup menu state, and zero or more script-supporting elements.

I would recommend against using `menu` as it might cause issues once it's actually supported in Firefox OS.

**Comment by soapdog** [comment]
I am using menu because the Building Blocks use menu... They created the thing like that, I don't like it either.

**Comment by marcoscaceres** [comment]
That's going to burn them in the long run... looks like I'm going to have to file bugs on the Mozilla side :(
